#!/bin/sh

logger -t firewall "interface '$INTERFACE' ($DEVICE) change detected"

has_zone() {
	fw4 -q network "$INTERFACE" >/dev/null && return 0
	eval $(ubus call "network.interface.$INTERFACE" status | jsonfilter -e 'ZONE=@.data.zone')
	fw4 -q zone "$ZONE" >/dev/null
}

do_exit() {
	logger -t firewall  "No firewall enabled" 
	exit 0
}

logger -t firewall "ACTION=$ACTION, IFUPDATE_ADDRESSES=$IFUPDATE_ADDRESSES, IFUPDATE_DATA=$IFUPDATE_DATA"

[ "$ACTION" = ifup -o "$ACTION" = ifupdate ] || exit 0
[ "$ACTION" = ifupdate -a -z "$IFUPDATE_ADDRESSES" -a -z "$IFUPDATE_DATA" ] && exit 0

/etc/init.d/firewall enabled || do_exit

has_zone || exit 0

logger -t firewall "Reloading firewall due to $ACTION of $INTERFACE ($DEVICE)"
/etc/init.d/firewall reload
